### ISSUE TITLE
Implementation ECTR 5.2.6.3

### ISSUE THREAD

**Issue by MaFINman** [dogoodthings/OSGiExamples-OBTab-Part5#1]
Hi,
is it possible to implement it in the new ECTR 5.2.6?
I get a error-message in ECTR Debug.log in the "Start OSGI framework" section:
`Starting bundle: [ ERROR    ] -> org.dogoodthings.ectr.OSGi-Examples-OBTab-Part5 [7](R 7.0): missing requirement [org.dogoodthings.ectr.OSGi-Examples-OBTab-Part5 [7](R 7.0)] osgi.wiring.package; (&(osgi.wiring.package=org.osgi.framework)(version>=1.8.0)(!(version>=1.9.0))) Unresolved requirements: [[org.dogoodthings.ectr.OSGi-Examples-OBTab-Part5 [7](R 7.0)] osgi.wiring.package; (&(osgi.wiring.package=org.osgi.framework)(version>=1.8.0)(!(version>=1.9.0)))]`

I tried to bind the org.osgi.framework with following in the pom.xml:
```
<dependency>
			<groupId>org.osgi</groupId>
			<artifactId>org.osgi.framework</artifactId>
			<version>1.8.0</version>
			<scope>provided</scope>
		</dependency>
```

instead of the original:
```
		<dependency>
			<groupId>org.osgi</groupId>
			<artifactId>org.osgi.core</artifactId>
			<version>6.0.0</version>
			<scope>provided</scope>
		</dependency>
```

But that didn't help.

Thanks for your help.
MaFIN

**Comment by dogoodthings** [comment]
Yes, you just have to change a pom.xml a little bit.Take a look at pom.xml of the example "TransformationOperation"The relevant changes are under tag <instuctions>, especially the _noee entry.    --Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 03.04.23, 14:32 schrieb MaFINman ***@***.***>:

   
  Hi, is it possible to implement it in the new ECTR 5.2.6? I get a error-message in ECTR Debug.log in the "Start OSGI framework" section: Starting bundle: [ ERROR ] -> org.dogoodthings.ectr.OSGi-Examples-OBTab-Part5 [7](R 7.0): missing requirement [org.dogoodthings.ectr.OSGi-Examples-OBTab-Part5 [7](R 7.0)] osgi.wiring.package; (&(osgi.wiring.package=org.osgi.framework)(version>=1.8.0)(!(version>=1.9.0))) Unresolved requirements: [[org.dogoodthings.ectr.OSGi-Examples-OBTab-Part5 [7](R 7.0)] osgi.wiring.package; (&(osgi.wiring.package=org.osgi.framework)(version>=1.8.0)(!(version>=1.9.0)))] 
  I tried to bind the org.osgi.framework with following in the pom.xml:  org.osgi org.osgi.framework 1.8.0 provided  
  instead of the original:  org.osgi org.osgi.core 6.0.0 provided  
  But that didn't help. 
  Thanks for your help. MaFIN

**Comment by MaFINman** [comment]
Thank you very much for the very quick help.
I copied the <instructions> part and pasted it into my pom. xml and it works.
Now I can adapt enlargement to our needs.

**Comment by dogoodthings** [comment]
Don't forget to change groupId / artifactId / version of your own new osgi bundle.

**Comment by itwangjian** [comment]
Hi, 
Is there a way to debug or do you know how to run ECTR with java remote debug?
Looking forward to your feedback, thanks

**Comment by dogoodthings** [comment]
Sorry for a late response - although i don't have exact instructions, i'm pretty sure you can debug ECTR using remote debug settings. Take a look into  <INST_DIR>\basis\config\jvm-config.xml - you can set any remote debug parameters there inside `<options>`
